### ISSUE TITLE
[Feature Request]: Specify folder for save

### ISSUE THREAD

**Issue by pcause** [Yohh/obsidian-simple-sketch#6]
### What would you like to see?

- Allow an option to specify the folder to save sketches in
- if you can, instead of fixed, when the user clicks the save icon, ask for a folder name and save there

### What problem would this feature solve?

supports a user's preferred organization strategy

**Comment by Yohh** [comment]
hi, thanks for your request.

I'm sorry for being late since you opened this issue, I'm very busy right now (too much than I thought at first release).

I have made a modal in order to set a custom title, filled with a placeholder, and a selector to select any existing folder in your vault. It will be available at next release.
